name: GitHub Actions Demo
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
     
      - name: Compiling imgRead.c
        run: |
          gcc imgRead.c -o imgRead_gcc
      - run: echo "🍏 This job's status is ${{ job.status }}."
